### ISSUE TITLE
Add high speed connector to mezzanine template.

### ISSUE THREAD

**Issue by mwelling** [96boards/mezzanine-community#10]
The mezzanine template currently only has low speed connector options.

**Comment by sdrobertw** [comment]
Let's start a to-do list on the template README.md

I have already modified the section in PR

**Comment by mwelling** [comment]
Okay, I merged just merged your PR. Go ahead and add it to the README.

**Comment by GustavoRP** [comment]
The Altium template already has the high-speed connector. However, I would like someone to check if it is in the exactly right position because the mechanical documentation I found did not have enough information about this connector.

**Comment by mwelling** [comment]
I will take a look before I merge it.

**Comment by sdrobertw** [comment]
This template has been merged, can we close this issue?

**Comment by GustavoRP** [comment]
The high-speed connector still needs to be added to the KiCad project. Unfortunately, I have no experience with it, but here is the footprint specification if someone wants to add it on the board:
http://portal.fciconnect.com/Comergent/fci/drawing/61083.pdf

**Comment by mwelling** [comment]
I will take care of it.

**Comment by GustavoRP** [comment]
we can close the issue, then.

**Comment by mwelling** [comment]
After I take care of it. :)

**Comment by mwelling** [comment]
KiCAD template has been updated to include the high-speed connector.
