### ISSUE TITLE
Meeting: Agenda 16th Sept 2019

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#108]
New Meeting Room: https://zoom.us/j/6199314558 4PM UTC

@mwelling
@ric96
@sdrobertw
@Mani-Sadhasivam
@tbewley
@ASerbinski

**Comment by Thore-Krug** [comment]
Is the meeting today ?

**Comment by Mani-Sadhasivam** [comment]
@Thore-Krug Yes, going on currently!

**Comment by Thore-Krug** [comment]
Dang it
