### ISSUE TITLE
Meeting Agenda 04th Dec 2017

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#39]
# Agenda
- Fritzing template: got corrected pin pitch from the fritzing forums
- @mwelling: Updates on GPS Mezzanine?
- @sdrobertw: updates on Akira's Drone Mezzanine?

Tagging:
@mwelling 
@glikely 
@sdrobertw 
@GustavoRP 
@rafaelchrist

**Comment by sdrobertw** [comment]
@ric96 

No updates on Akira's drone board just yet. We hope to have this board added to repo asap.

**Comment by mwelling** [comment]
Send the first GPS mezzanine PCB out to OSHPark for fab.

**Comment by ric96** [comment]
# Meeting Notes
- Expecting Akira's Drone Mezzanine to be pushed into the repo soon
- People are interested in using this repo to host other 96boards related hardware designs, but it's decided to keep the scope of this repo limited to mezzanine for now
