### ISSUE TITLE
Meeting Agenda 08th Jan 2018

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#44]
# Agenda

@sdrobertw Updates on AiStarvision and Akira's Drone Mezz?

tagging
@mwelling 
@rafaelchrist

**Comment by sdrobertw** [comment]
- Waiting on response from AiStarVision and Akira for drone mezzanine integration into repo.
   - Also trying to get Chris Taylors 2.0->2.54mm pitch converter mezzanine into repo.
- @sdrobertw to get Cadence to join next meeting to discuss I2S mezzanine for DSP AOSP upstream efforts. To ping Niranjan.
- I2S mezzanine to take next on list (possibly followed by Touchpad mezzanine
- Touchpad mezzanine mentioned by Dmitry
   - https://www.pi-supply.com/product/flick-hat-3d-tracking-gesture-hat-raspberry-pi/
- Barry's micromezz is still waiting for legal approval - once cleared will make it's way into repo.
- Try to get Grant back into call for next meeting
- Thermal mezzanine - no movement.
- Add e-ink mezzanine into issues.
- Michael to possibly work on an FPGA mezzanine
- Talked with group about ECE 191 project and future potential of pushing a mezzanine project for another quarter. Introduce students to this initiative.
- Discussions on open tool chain for FPGA based hardware. Could Linaro work on this?
