### ISSUE TITLE
Meeting: Agenda - 05, March 2018

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#50]
Meeting time: 5:00PM UTC

Please comment for next meeting's agenda items:

@glikely
@mwelling
@ric96
@sdrobertw
@krisik70

Notes will be added to this card after the meeting.

**Comment by sdrobertw** [comment]
- Micro Mezzanine approval has cleared (AFAIK). We will be expecting some contribution from Barry soon.
- Still waiting on Katagarsu Red Mezzanine contribution from Akira
- Migrating UART Mezzanine over to Repo soon
- Work on e-ink mezzanine to come after Connect HKG18

**Comment by ric96** [comment]
- Chris Tyler is fine with us hosting the 2mm to 2.54 mm header mezzanine, although he would like a newer revision to be added.

**Comment by ukBaz** [comment]
Does this mean the meeting has happened?

The meeting is scheduled for 17:00 UTC. 
https://github.com/96boards/mezzanine-community#meeting-notes
Currently it is 16:45 UTC

**Comment by ric96** [comment]
@ukBaz
it's going to happen in about 15min, these are the topics we will be discussing in greater detail

**Comment by sdrobertw** [comment]
https://upverter.com/ukBaz/0f2a430ab12afa2e/micromez/

**Comment by sdrobertw** [comment]
@ukBaz Will need to update that time. Thanks for letting us know!

**Comment by ric96** [comment]
@sdrobertw time is fine

**Comment by sdrobertw** [comment]
- Dmitry: Mezzanine that brings in a battery and touch screen. 
- Ragnar: This kicad tutorial series was recommended on a local forum recently: https://www.youtube.com/watch?v=JN_Y93RTdSo&list=PL5iUxv3Op2fOpVASHvcpM2O4UO0yMfKJi
- Barry: https://www.buydisplay.com/default/10-1-inch-1024x600-50-pins-tft-lcd-display-w-touch-panel-and-touch-driver

**Comment by sdrobertw** [comment]
http://www.guru3d.com/articles-pages/wireless-graphics-card-kfa2-gtx-460-wdhi-review,1.html

**Comment by sdrobertw** [comment]
Attendees:

- Barry
- Dmitry
- Ivan Farkas
- Michael Welling
- Pan
- Ragnar
- Sahaj
- Robert Wolff

**Comment by sdrobertw** [comment]
KiCAD Discussion as repo standard: http://kicad-pcb.org/
