### ISSUE TITLE
Question: how much space above USB ports

### ISSUE THREAD

**Issue by Genoil** [96boards/mezzanine-community#51]
I've just started working on a mezzanine based on your template (thanks!). Although I understand the meaning of the keepout areas, I was wondering how much room there really is between the USB type A ports and the mated mezzanine. With a PCB distance of 7mm and a USB-A receptacle of ±5.5mm, I should be able to place some small 1mm height parts there, right? Or is this asking for problems?

(btw I am using both 60pin and 40pin headers)

**Comment by mwelling** [comment]
I would not recommend any through-hole or bottom side components in these keep out areas.

**Comment by Genoil** [comment]
It is only an FPC header for connecting a DSI panel but I think I found a better place for it already. Thanks.
