### ISSUE TITLE
low speed connector in schematic is female receptacle, not male header

### ISSUE THREAD

**Issue by Genoil** [96boards/mezzanine-community#53]
The 55510-140LF low speed connector listed in the (Eagle, didn't check others) schematic is actual the female part. It should be the 57102 (TH) or 57202 (SMT) 

See https://cdn.amphenol-icc.com/media/wysiwyg/files/documentation/datasheet/boardwiretoboard/bwb_minitek_unshrouded_vh.pdf

**Comment by mwelling** [comment]
@rafaelchrist Can you take a look into this?

**Comment by mwelling** [comment]
Thanks @jveitchmichaelis !
