### ISSUE TITLE
Meeting: Agenda 25th Jun 2018

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#66]
Meeting time: 4:00PM UTC
Please comment on next meeting's agenda items:
@glikely
@mwelling
@ric96
@sdrobertw
@krisik70
@Mani-Sadhasivam

**Comment by sdrobertw** [comment]
- New student designed battery mezzanine to make it's way into the repo

**Comment by ric96** [comment]
- Upcoming mezzanine poll google form

**Comment by sdrobertw** [comment]
- Bryan: Working with partner on mezzanine, just prototyping - Expand with lots of different things, extra sockets on board, etc... Variety of plug in modules will come with it. Looking at September for demoing at Linaro Connect. Working on getting it validated with Ultra96
- GPS Mezzanine discussion for crowd funding.
- Ragnar: New UBLOX module A new ublox module could be interesting... still not even ES available. http://en.ctimes.com.tw/DispProduct.asp?O=HK254CA1YC6SAA00PZ

**Comment by sdrobertw** [comment]
- Need to do more research on market, and what the community wants before the next crowd funding event. 
- Publish a mezzanine "Go" page
- Create a marketing form to find out what mezzanines people are interested in and at what price points people are willing to buy them at.

**Comment by tbewley** [comment]
HI guys - I lead a group at UC San Diego and we are working on some new boards focused on DC motor / stepper / servo control (for small mobile robotics, 3d printers, etc), encoder counting, battery management, etc (an outgrowth of the BeagleBone Blue project which we were closely involved with).  We're now building a breakout board for the RPi and we were planning on making a modified version of this board for the 96B CE spec (410c, etc).  Then I saw this:  https://www.96boards.org/blog/community-mezzanine-board/  which struck me as a very good idea - an aspect of this idea is to morph any 96B CE board low spead header so it can mate to an RPi HAT, while breaking out some key features of the high-speed header.  Has anyone carried this idea over the finish line, or are plans in the process to do so?  If not, my team might be interested in doing this...   Anyway, maybe I'll join your next meet to explore this question?  cheers - Tom

**Comment by sdrobertw** [comment]
@tbewley Would you mind dropping me an email at robert.wolff@linaro.org ?
