### ISSUE TITLE
Meeting: Agenda 9th Jul 2018

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#68]
Meeting time: 4:00PM UTC
Please comment on next meeting's agenda items:

@mwelling
@ric96
@sdrobertw
@Mani-Sadhasivam
@tbewley
@ASerbinski

**Comment by tbewley** [comment]
Dear Sahaj et al -
I’m so sorry I missed this meeting, I was giving a talk at the SIAM annual meeting in Portland at precisely this time.  
I look forward to working with you guys (related to my lab's work on a new robotics-oriented mezzanine board) at the next available opportunity.
Feel free to reach out to me at this email in the meantime.
Best regards,
- Tom

—
Thomas Bewley, Professor, UC San Diego   (m: +1.858.643.1109, schedule <http://robotics.ucsd.edu/schedule>, LinkedIn <https://www.linkedin.com/in/thomas-bewley/detail/recent-activity/>)
Director, UCSD Flow Control & Coordinated Robotics Labs <http://robotics.ucsd.edu/>
Founder, Renaissance Robotics <https://renaissancerobotics.com/> · educational robotics kits ·  bespoke resources for embedded prototyping
Senior Consultant, Robotics & Controls, ATA Engineering <http://www.ata-e.com/>
