### ISSUE TITLE
Meeting: Agenda 26th Nov 2018

### ISSUE THREAD

**Issue by ric96** [96boards/mezzanine-community#85]
Meeting time: 5:00PM UTC
Please comment on the next meeting's agenda items:

@mwelling
@ric96
@sdrobertw
@Mani-Sadhasivam
@tbewley
@ASerbinski

**Comment by ASerbinski** [comment]
I won't be able to make it today.

**Comment by ric96** [comment]
Meeting Notes:
Richard(ADI): Working on Multiple mezzanines with Arrow
Mani: Will be updating the I2S Mezzanine design as per Michael's suggestions.
Robert: l working on Contest material.
Michael: pushing on getting i2s mezzi on groupgets
